name: DevSecOps CI Pipeline

permissions:
  contents: read

on:
  push:
    branches: [ "main" ]

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Dependencies
      run: npm install

    # 🔍 SEMGREP (SAST)
    - name: Run Semgrep
      run: |
        pip install semgrep
        semgrep scan --config=auto

    # 🔐 GITLEAKS (Secrets)
    - name: Run Gitleaks
      uses: gitleaks/gitleaks-action@v2

    # 📦 SNYK (Dependencies)
    - name: Run Snyk
      uses: snyk/actions/node@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    # 🐳 BUILD DOCKER IMAGE
    - name: Build Docker Image
      run: docker build -t devsecops-app .

    # 🐳 TRIVY (Container Scan)
    - name: Scan Docker Image
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: devsecops-app

    # 🏗️ CHECKOV (IaC SCAN)
    - name: Run Checkov
      uses: bridgecrewio/checkov-action@master
      with:
        skip_check: CKV_AWS_18,CKV_AWS_144,CKV_AWS_145,CKV2_AWS_61,CKV2_AWS_62

      # 🛡️ POLICY CHECK (BEST WAY)
    - name: Run Conftest
      uses: instrumenta/conftest-action@v0.3.0
      with:
        files: .
      continue-on-error: true
          
    # 🚀 DEPLOYMENT STAGES (SIMULATED)

    - name: Deploy to Dev
      if: success()
      run: echo "Deploying to Dev Environment..."

    - name: Deploy to Staging
      if: success()
      run: echo "Deploying to Staging Environment..."

    - name: Deploy to Production
      if: success()
      run: echo "Deploying to Production Environment..."